name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK platforms & build-tools
        run: |
          yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      # Unzip the uploaded project ZIP into ./project
      - name: Unzip project
        run: |
          if [ ! -f Accountability_Project.zip ]; then
            echo
