name: Accountability_Project (3) — Unzip

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional safety: ensure unzip is available (usually preinstalled on ubuntu)
      - name: Ensure unzip is installed
        run: |
          if ! command -v unzip >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y unzip
          fi

      # Clean any previous extracted folder so we always get a fresh state
      - name: Remove previous extracted folder if present
        run: |
          rm -rf "Accountability_Project"

      - name: Unzip Accountability_Project (3).zip into Accountability_Project/
        run: |
          unzip -o "Accountability_Project (3).zip" -d "Accountability_Project"

      # Quick sanity check (you can delete this if you don't need it)
      - name: List extracted contents
        run: |
          echo "Extracted files:"
          ls -la "Accountability_Project"
