- name: Find and validate AndroidManifest.xml (fail-fast with line/col)
        shell: bash
        run: |
          set -euo pipefail
          echo "=== Searching for AndroidManifest.xml files ==="
          mapfile -d '' manifests < <(find "$PROJECT_DIR" -type f -name AndroidManifest.xml -print0 || true)
          if [ ${#manifests[@]} -eq 0 ]; then
            echo "ERROR: No AndroidManifest.xml found under $PROJECT_DIR"; exit 1
          fi
          err=0
          for f in "${manifests[@]}"; do
            echo "----- $f -----"
            # show first 120 lines with numbers
            nl -ba "$f" | sed -n '1,120p'
            echo "Validating XML..."
            if ! xmllint --noout "$f" 2>xml.err; then
              echo "xmllint error:"
              cat xml.err
              # extract line number if present and print context
              line=$(sed -n 's/.*line \([0-9]\+\).*/\1/p' xml.err | head -n1 || true)
              if [ -n "$line" ]; then
                start=$(( line>3 ? line-3 : 1 ))
                end=$(( line+3 ))
                echo "Context around line $line:"
                nl -ba "$f" | sed -n "${start},${end}p"
              fi
              err=1
            else
              echo "OK"
            fi
            echo
          done
          exit $err
