name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK platforms & build-tools
        run: |
          yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      # Unzip your project that you uploaded to the repo root
      - name: Unzip project
        run: |
          if [ ! -f Accountability_Project.zip ]; then
            echo "Accountability_Project.zip not found in repo root"; exit 1
          fi
          rm -rf project
          unzip -q Accountability_Project.zip -d project
          # If the zip has a single top folder, move its contents up
          INNER=$(find project -mindepth 1 -maxdepth 1 -type d | head -n 1)
          if [ -d "$INNER/app" ] && [ -f "$INNER/settings.gradle" ]; then
            shopt -s dotglob
            mv "$INNER"/* project/
          fi
          ls -la project

      - name: Build debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: project
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: accountability-debug-apk
          path: project/app/build/outputs/apk/debug/app-debug.apk
